name: Java CI and Deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Run Tests
      run: mvn test

    - name: Archive JAR/WAR
      if: success()
      run: |
        mkdir -p artifacts
        cp target/*.jar artifacts/ || cp target/*.war artifacts/
      # The above command copies the generated JAR or WAR to the 'artifacts' directory

    - name: Commit and Push JAR/WAR
      if: success()
      run: |
        git config --local user.email "manjug.dr@gmail.com"
        git config --local user.name "manjugdr"
        git checkout -b artifacts || git checkout artifacts
        cp -R artifacts/* .
        git add .
        git commit -m "Add built JAR/WAR file"
        git push origin artifacts --force
